blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/orgs/Writers-of-the-Script/discussions
    about: Got a suggestion? Great! Post it here.
  - name: Our Discord
    url: https://discord.gg/nullnullnullnull
    about: Having trouble getting the mod running? Got questions? Ask in our Discord!
